// Package scheduler implements a game-time-aware daily schedule for NPCs.
//
// Each NPC can have one active daily schedule consisting of (game_hour, action)
// entries. The schedule is generated by the NPC's LLM at the start of each day
// (via the npc_plan_day MCP tool) and cleared on the next day_started event.
//
// The Tick method is called on every game-time-hour change. When an entry's
// game_hour matches the current hour, it is marked as "fired" and returned to
// the caller for dispatch (typically as a schedule_trigger synthetic event
// through hermesrelay).
package scheduler

import (
	"sync"
	"time"

	"github.com/OmniStormX/SmartNPC/pkg/workflow"
)

// Entry is one slot in an NPC's daily schedule.
//
// A schedule entry intentionally records ONLY the tool name and the
// reasoning. Concrete tool parameters (location, duration, message
// content, item id, etc.) are deferred to the moment the entry fires:
// the LLM will pick them then based on live game state instead of
// committing to numbers ahead of time.
//
// Time precision: minute-of-day from midnight (06:00 = 360, 25:30 = 1530).
// GameHour is kept for backward compatibility with older callers / logs;
// it is derived from GameMinutes when not set explicitly.
type Entry struct {
	GameHour    int       `json:"game_hour"            jsonschema:"6-25, the hour the entry fires (10-minute precision via game_minute)"`
	GameMinute  int       `json:"game_minute,omitempty" jsonschema:"0-50 in 10-minute steps; defaults to 0 if absent"`
	GameMinutes int       `json:"game_minutes,omitempty" jsonschema:"derived: hour*60 + minute (used internally; no need to set)"`
	Action      string    `json:"action"               jsonschema:"MCP tool name, e.g. \"npc_water_crops\""`
	Reason      string    `json:"reason,omitempty"     jsonschema:"LLM's reasoning (for debugging / display)"`
	Fired       bool      `json:"fired"                jsonschema:"set true once dispatched"`
	FiredAt     time.Time `json:"fired_at,omitempty"`

	// ── P3 workflow fields ────────────────────────────────────────────
	// Every entry carries either WorkflowID (built-in), Workflow (inline), or
	// both (legacy action auto-wrapped as a 1-step Workflow). The scheduler
	// itself treats these as opaque payload — the engine (P4) interprets them.
	WorkflowID string               `json:"workflow_id,omitempty"`
	Workflow   *workflow.Definition `json:"workflow,omitempty"`
	Args       map[string]any       `json:"args,omitempty"`
}

// MinutesOfDay returns the entry's fire time as a minute-of-day count
// (06:00 → 360). Falls back to GameHour*60 when GameMinutes is unset so
// older serialized schedules keep working unchanged.
func (e Entry) MinutesOfDay() int {
	if e.GameMinutes > 0 {
		return e.GameMinutes
	}
	return e.GameHour*60 + e.GameMinute
}

// DaySchedule holds one NPC's plan for one game day.
type DaySchedule struct {
	NPC     string  `json:"npc"`
	Day     int     `json:"day"`    // 1-28
	Season  string  `json:"season"` // spring/summer/fall/winter
	Year    int     `json:"year"`
	Entries []Entry `json:"entries"`
}

// FiredEntry is returned by Tick when a schedule entry's time arrives.
type FiredEntry struct {
	NPC         string `json:"npc"`
	GameHour    int    `json:"game_hour"`
	GameMinute  int    `json:"game_minute"`
	GameMinutes int    `json:"game_minutes"`
	Action      string `json:"action"`
	Reason      string `json:"reason,omitempty"`
	// ── P3 workflow fields ────────────────────────────────────────────
	WorkflowID string               `json:"workflow_id,omitempty"`
	Workflow   *workflow.Definition `json:"workflow,omitempty"`
	Args       map[string]any       `json:"args,omitempty"`
}

// Scheduler manages daily schedules for all NPCs. Thread-safe.
type Scheduler struct {
	mu        sync.RWMutex
	schedules map[string]*DaySchedule // keyed by NPC name (lowercase)
	agentNPCs []string                // all agent-managed NPC names (set at startup)
}

// New creates a new empty Scheduler.
func New() *Scheduler {
	return &Scheduler{
		schedules: make(map[string]*DaySchedule),
	}
}

// SetAgentNPCs stores the full list of agent-managed NPC names. This list is
// used when npc_plan_day is called with npc="*" to expand into all NPCs.
func (s *Scheduler) SetAgentNPCs(names []string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.agentNPCs = make([]string, len(names))
	copy(s.agentNPCs, names)
}

// AgentNPCs returns the registered agent NPC names.
func (s *Scheduler) AgentNPCs() []string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	out := make([]string, len(s.agentNPCs))
	copy(out, s.agentNPCs)
	return out
}

// SetSchedule stores or replaces a daily schedule for an NPC.
// Existing entries for that NPC are discarded.
func (s *Scheduler) SetSchedule(sched DaySchedule) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.schedules[sched.NPC] = &sched
}

// AlreadyPlannedToday reports whether the NPC already has a schedule for this
// game day. Used by npc_plan_day to warn the LLM it's re-planning the same day.
func (s *Scheduler) AlreadyPlannedToday(npc string, day int, season string) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	sched := s.schedules[npc]
	if sched == nil {
		return false
	}
	return sched.Day == day && sched.Season == season
}

// GetSchedule returns the current day's schedule for an NPC.
// Returns nil if no schedule is set.
func (s *Scheduler) GetSchedule(npc string) *DaySchedule {
	s.mu.RLock()
	defer s.mu.RUnlock()
	sched := s.schedules[npc]
	if sched == nil {
		return nil
	}
	// Return a copy to avoid data races.
	cp := *sched
	entries := make([]Entry, len(sched.Entries))
	copy(entries, sched.Entries)
	cp.Entries = entries
	return &cp
}

// ClearAll removes all schedules (called on day_started).
func (s *Scheduler) ClearAll() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.schedules = make(map[string]*DaySchedule)
	// fmt.Fprintln(os.Stderr, "\033[34m[schedule]: =========clear =========\033[0m")
}

// ClearNPC removes the schedule for a specific NPC.
func (s *Scheduler) ClearNPC(npc string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	delete(s.schedules, npc)
}

// Tick checks all schedules against the given absolute minute-of-day and
// returns entries that should fire now. Each entry fires at most once per
// day. Entries whose fire time is at or before the current minute are
// fired, so skipped ticks (sleep, cutscene, debug time-jump, 20-minute
// tick cadence missing a 10-minute entry) are never lost.
//
// gameMinutes is hour*60 + minute (06:00 → 360, 25:00 → 1500). For
// backward compatibility with callers that still pass an hour (≤ 30,
// matches SDV's 6-25 range plus a margin), we promote it to hour*60.
func (s *Scheduler) Tick(gameMinutes int) []FiredEntry {
	s.mu.Lock()
	defer s.mu.Unlock()

	// Backward-compat: legacy callers passed an integer hour. Anything ≤ 30
	// can't be a minute-of-day count (>= 360 in practice), so treat it as
	// an hour and promote.
	if gameMinutes <= 30 {
		gameMinutes *= 60
	}

	var fired []FiredEntry
	now := time.Now()

	for npc, sched := range s.schedules {
		for i := range sched.Entries {
			e := &sched.Entries[i]
			if e.Fired {
				continue
			}
			if e.MinutesOfDay() > gameMinutes {
				continue
			}
			e.Fired = true
			e.FiredAt = now
			fired = append(fired, FiredEntry{
				NPC:         npc,
				GameHour:    e.GameHour,
				GameMinute:  e.GameMinute,
				GameMinutes: e.MinutesOfDay(),
				Action:      e.Action,
				Reason:      e.Reason,
				WorkflowID:  e.WorkflowID,
				Workflow:    e.Workflow,
				Args:        e.Args,
			})
		}
	}
	return fired
}

// PendingEntries returns all entries that have NOT yet fired for an NPC,
// sorted by game_hour ascending. Useful for npc_get_schedule tool.
func (s *Scheduler) PendingEntries(npc string) []Entry {
	s.mu.RLock()
	defer s.mu.RUnlock()
	sched := s.schedules[npc]
	if sched == nil {
		return nil
	}
	var pending []Entry
	for _, e := range sched.Entries {
		if !e.Fired {
			pending = append(pending, e)
		}
	}
	return pending
}

// AllNPCs returns the names of all NPCs that have a schedule set.
func (s *Scheduler) AllNPCs() []string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	npcs := make([]string, 0, len(s.schedules))
	for npc := range s.schedules {
		npcs = append(npcs, npc)
	}
	return npcs
}
