using System.Collections.Generic;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using StardewModdingAPI;
using StardewModdingAPI.Events;
using StardewValley;

namespace SmartNPC.Bridge
{
    internal sealed class XiaMiData
    {
        private const string NpcName = "XiaMi";

        // Spawn tile on the Farm map — near the farmhouse door (player spawn area).
        private static readonly Vector2 SpawnTile = new(64, 15);

        // ── Spritesheet frame indices (generated by build_spritesheet.py) ──
        // Walk: front
        public const int FrameFrontStart = 0;   // front_01..front_08 = idx 0..7
        public const int FrameFrontEnd = 7;
        // Walk: back
        public const int FrameBackStart = 8;    // back_01..back_08 = idx 8..15
        public const int FrameBackEnd = 15;
        // Walk: left
        public const int FrameLeftStart = 16;   // side_left_01..08 = idx 16..23
        public const int FrameLeftEnd = 23;
        // Hoe action
        public const int FrameHoeStart = 24;    // hoe_01..09 = idx 24..32
        public const int FrameHoeEnd = 32;
        // Watering
        public const int FrameWaterStart = 33;  // watering_01..07 = idx 33..39
        public const int FrameWaterEnd = 39;
        // Hold items
        public const int FrameHoldPumpkin = 40;
        public const int FrameHoldCrop = 41;
        public const int FrameHoldFlower = 42;
        public const int FrameIdleStand = 43;
        public const int FrameHoldChicken = 44;
        // Emotes
        public const int FrameEmoteCheer = 45;
        public const int FrameEmoteHeart = 46;
        public const int FrameEmoteSurprised = 47;
        public const int FrameEmoteSleepy = 48;

        private readonly IModHelper _helper;
        private readonly IMonitor _log;

        private NPC? _npc;

        public XiaMiData(IModHelper helper, IMonitor log)
        {
            _helper = helper;
            _log = log;
        }

        public void Register(IModEvents events)
        {
            events.Content.AssetRequested += this.OnAssetRequested;
            events.GameLoop.SaveLoaded += this.OnSaveLoaded;
            events.GameLoop.DayStarted += this.OnDayStarted;
        }

        // ── Spawn / Day logic ──────────────────────────────────────────

        private void OnSaveLoaded(object? sender, SaveLoadedEventArgs e)
        {
            this.SpawnNpc();
        }

        private void OnDayStarted(object? sender, DayStartedEventArgs e)
        {
            // Re-position at spawn point each morning (simple schedule).
            if (_npc != null)
            {
                var farm = Game1.getFarm();
                if (!farm.characters.Contains(_npc))
                    farm.addCharacter(_npc);

                _npc.Position = SpawnTile * 64f;
                _npc.faceDirection(2); // face down
            }
        }

        private void SpawnNpc()
        {
            var farm = Game1.getFarm();
            if (farm == null) return;

            // Remove stale instance if present (e.g. hot-reload).
            for (int i = farm.characters.Count - 1; i >= 0; i--)
            {
                if (farm.characters[i]?.Name == NpcName)
                    farm.characters.RemoveAt(i);
            }

            // Create the NPC instance. The game automatically loads
            // Characters/XiaMi sprite + Portraits/XiaMi from our asset hooks.
            _npc = new NPC(
                sprite: new AnimatedSprite($"Characters\\{NpcName}", 0, 16, 32),
                position: SpawnTile * 64f,
                defaultMap: "Farm",
                facingDirection: 2,
                name: NpcName,
                datable: false,
                portrait: Game1.content.Load<Texture2D>($"Portraits\\{NpcName}")
            );

            // Make NPC interactive (clickable for dialogue).
            _npc.displayName = "\u590f\u5f25"; // 夏弥
            _npc.willDestroyObjectsUnderfoot = false;
            _npc.IsWalkingTowardPlayer = false;

            farm.addCharacter(_npc);
            _log.Log($"[XiaMi] NPC spawned at Farm ({SpawnTile.X}, {SpawnTile.Y})", LogLevel.Info);
        }

        // ── Asset hooks ────────────────────────────────────────────────

        private void OnAssetRequested(object? sender, AssetRequestedEventArgs e)
        {
            if (e.NameWithoutLocale.IsEquivalentTo($"Characters/{NpcName}"))
            {
                e.LoadFromModFile<Texture2D>("assets/xiami/XiaMi_spritesheet.png", AssetLoadPriority.Medium);
            }
            else if (e.NameWithoutLocale.IsEquivalentTo($"Portraits/{NpcName}"))
            {
                e.LoadFromModFile<Texture2D>("assets/xiami/XiaMi_Portrait.png", AssetLoadPriority.Medium);
            }
            else if (e.NameWithoutLocale.IsEquivalentTo("Data/NPCDispositions"))
            {
                e.Edit(asset =>
                {
                    var data = asset.AsDictionary<string, string>();
                    // Format: age/manner/anxiety/optimism/gender/datable/love/home-region/birthday/friends/name/...
                    data.Data[NpcName] = "adult/neutral/outgoing/positive/female/not-datable/null/Other/spring 1/" +
                        $"//{NpcName}/Farm 64 15/{NpcName}";
                });
            }
            else if (e.NameWithoutLocale.IsEquivalentTo($"Characters/Dialogue/{NpcName}"))
            {
                e.LoadFrom(() => new Dictionary<string, string>
                {
                    ["Introduction"] = "哼哼，你就是这个农场的主人？看起来比我想象的要……普通嘛。$h#$e#开玩笑的啦，我叫夏弥。以后多多指教？",
                    ["Mon"] = "早呀。你今天看起来也一副没睡醒的样子，真让人担心呢。$h",
                    ["Tue"] = "欸？你是在等我吗？早说嘛，我可以假装很感动一下。$h",
                    ["Wed"] = "今天风不错，适合散步，也适合逃课——开玩笑的啦。$h",
                    ["Thu"] = "你这个表情也太好懂了吧，真的不适合藏秘密。$h",
                    ["Fri"] = "笨蛋。不是所有事情都要靠勇气解决的，有时候还需要一点点脑子。$h",
                    ["Sat"] = "有时候我会想，普通人的一天到底是什么样子的。$s",
                    ["Sun"] = "如果什么都不用背负，只是吃饭、散步、回家……听起来好像也不错。$s",
                }, AssetLoadPriority.Medium);
            }
            else if (e.NameWithoutLocale.IsEquivalentTo($"Characters/schedules/{NpcName}"))
            {
                // Schedule: simple patrol around the farm.
                // Format: time map x y facing_direction [animation]
                e.LoadFrom(() => new Dictionary<string, string>
                {
                    ["spring"] = "610 Farm 64 15 2/1000 Farm 68 18 2/1400 Farm 60 20 0/1800 Farm 64 15 2",
                    ["summer"] = "610 Farm 64 15 2/1000 Farm 70 16 1/1400 Farm 58 19 3/1800 Farm 64 15 2",
                    ["fall"]   = "610 Farm 64 15 2/1000 Farm 66 20 2/1400 Farm 62 14 0/1800 Farm 64 15 2",
                    ["winter"] = "610 Farm 64 15 2/1000 Farm 65 16 2/1400 Farm 63 17 0/1800 Farm 64 15 2",
                }, AssetLoadPriority.Medium);
            }
        }
    }
}
