# scripts/generate_compose.ps1
# Generates deploy/hermes/docker-compose.yml from hermes/npcs.yaml.
# Usage: powershell -NoProfile -File scripts/generate_compose.ps1 [-RepoRoot <path>]

param(
    [string]$RepoRoot
)

if (-not $RepoRoot) {
    $RepoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
}

$Registry = Join-Path $RepoRoot "hermes\npcs.yaml"
$OutputFile = Join-Path $RepoRoot "deploy\hermes\docker-compose.yml"

if (-not (Test-Path $Registry)) {
    Write-Error "NPC registry not found: $Registry"
    exit 1
}

# Parse npcs.yaml
$npcs = @()
$current = $null

foreach ($line in Get-Content $Registry -Encoding UTF8) {
    $line = $line -replace '#.*$', ''
    if ($line -match '^\s*-\s*id:\s*(\S+)') {
        if ($current) { $npcs += $current }
        $current = @{
            id = $Matches[1]
            gateway_port = ''
            enabled = 'true'
        }
    }
    elseif ($current -and $line -match '^\s*gateway_port:\s*(\d+)') {
        $current['gateway_port'] = $Matches[1]
    }
    elseif ($current -and $line -match '^\s*enabled:\s*(\S+)') {
        $current['enabled'] = $Matches[1]
    }
}
if ($current) { $npcs += $current }

$npcs = $npcs | Where-Object { $_['enabled'] -eq 'true' -and $_['gateway_port'] -ne '' }

if ($npcs.Count -eq 0) {
    Write-Error "No enabled NPCs found in $Registry"
    exit 1
}

# Build YAML content
$lines = @(
    "# AUTO-GENERATED by setup.bat via scripts/generate_compose.ps1"
    "# Source: hermes/npcs.yaml"
    "# Regenerate: run setup.bat"
    "#"
    "# DO NOT EDIT MANUALLY."
    ""
    "x-hermes-common: &hermes-common"
    "  build: ."
    "  restart: unless-stopped"
    "  env_file: .env"
    "  networks:"
    "    - smartnpc-net"
    ""
    "services:"
)

foreach ($npc in $npcs) {
    $id = $npc['id']
    $port = $npc['gateway_port']
    $lines += "  hermes-${id}:"
    $lines += "    <<: *hermes-common"
    $lines += "    container_name: hermes-${id}"
    $lines += "    environment:"
    $lines += "      NPC_PROFILE: ${id}"
    $lines += "      NPC_PORT: `"${port}`""
    $lines += "    ports:"
    $lines += "      - `"${port}:${port}`""
    $lines += "    healthcheck:"
    $lines += "      test: [`"CMD`", `"curl`", `"-sf`", `"http://localhost:${port}/health`"]"
    $lines += "      interval: 30s"
    $lines += "      timeout: 5s"
    $lines += "      retries: 3"
    $lines += "      start_period: 60s"
    $lines += ""
}

$lines += "networks:"
$lines += "  smartnpc-net:"
$lines += "    driver: bridge"

$content = ($lines -join "`n") + "`n"

$outputDir = Split-Path $OutputFile
if (-not (Test-Path $outputDir)) { New-Item -ItemType Directory -Path $outputDir -Force | Out-Null }

[System.IO.File]::WriteAllText($OutputFile, $content, (New-Object System.Text.UTF8Encoding $false))
Write-Host "Generated: $OutputFile ($($npcs.Count) NPC services)"
