#!/usr/bin/env bash
# Render per-NPC Hermes profile files from hermes/profiles/_master/ templates.
#
# Scope: renders everything EXCEPT SOUL.md. The six SOUL.md files are hand-
# written per-NPC personas and must never be touched by this script.
#
# NPC metadata is read from hermes/npcs.yaml.
# Placeholders (replaced by GNU sed):
#   {{NPC_NAME}}       PascalCase internal name (XiaMi, Abigail, ...)
#   {{NPC_DISPLAY}}    Chinese display name (夏弥, 阿比盖尔, ...)
#   {{NPC_DIR}}        lower-case profile directory name (xiami, abigail, ...)
#   {{NPC_PORT}}       Hermes Gateway API_SERVER_PORT
#   {{PEER_A_NAME}}    First peer, PascalCase
#   {{PEER_A_DISPLAY}} First peer, Chinese display name
#   {{PEER_B_NAME}}    Second peer, PascalCase
#   {{PEER_B_DISPLAY}} Second peer, Chinese display name
#
# Usage (from repo root):
#   bash scripts/render_profiles.sh
#
# Windows note: run inside WSL, e.g.
#   wsl -d Ubuntu-22.04 bash -c "cd /mnt/d/SmartNPC && bash scripts/render_profiles.sh"
#
# This script is idempotent: re-running produces the same output tree. The
# canonical sanity check is that `git diff hermes/profiles/xiami/` is empty
# after a render, because xiami is itself rendered from _master/.
#
# Do NOT edit rendered per-NPC files (skills/, config-overlay.yaml,
# cron-recipes.md, critical-policy.md) directly — they are regenerated on every render. Edit
# hermes/profiles/_master/ instead, then re-run this script.
#
# See ADR-0003 (docs/adr/0003-npc-name-placeholder-cloning.md) and
# docs/architecture.md § Profile cloning mechanism for the design rationale.

set -euo pipefail

# Resolve repo root relative to this script so it works regardless of cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MASTER="$REPO_ROOT/hermes/profiles/_master"
REGISTRY="$REPO_ROOT/hermes/npcs.yaml"
RUNTIME_CONFIG="$REPO_ROOT/hermes/runtime-config.yaml"

# shellcheck source=scripts/lib/npc_registry.sh
source "$REPO_ROOT/scripts/lib/npc_registry.sh"

if [ ! -d "$MASTER" ]; then
  echo "error: master template directory not found: $MASTER" >&2
  exit 1
fi

smartnpc_load_registry "$REGISTRY" || true

if [ "${#SMARTNPC_NPCS[@]}" -eq 0 ]; then
  echo "WARNING: no enabled NPCs in registry — generating empty outputs"

  # Write empty runtime-config.
  cat > "$RUNTIME_CONFIG" <<'EOF'
# hermes/runtime-config.yaml
#
# Generated by scripts/render_profiles.sh from hermes/npcs.yaml.
# No NPCs are currently enabled.

profiles: []
EOF
  echo "rendered: hermes/runtime-config.yaml (empty)"

  # Write mod NPC config — ALL disabled.
  MOD_NPC_JSON="$REPO_ROOT/smapi-mod/assets/agent_npcs.json"
  {
    echo "{"
    total_all=${#SMARTNPC_ALL_NPCS[@]}
    idx=0
    for DIR in "${SMARTNPC_ALL_NPCS[@]}"; do
      NAME="${SMARTNPC_NPC_GAME_NAME[$DIR]}"
      if [ $((idx + 1)) -lt "$total_all" ]; then
        echo "  \"$NAME\": false,"
      else
        echo "  \"$NAME\": false"
      fi
      idx=$((idx + 1))
    done
    echo "}"
  } > "$MOD_NPC_JSON"
  echo "rendered: smapi-mod/assets/agent_npcs.json ($total_all NPCs, all disabled)"
  echo ""
  echo "done. To enable NPCs, set enabled: true in hermes/npcs.yaml and re-run."
  exit 0
fi

for DIR in "${SMARTNPC_NPCS[@]}"; do
  NAME="${SMARTNPC_NPC_GAME_NAME[$DIR]}"
  DISP="${SMARTNPC_NPC_DISPLAY_NAME[$DIR]}"
  PORT="${SMARTNPC_NPC_GATEWAY_PORT[$DIR]}"
  PAN="${SMARTNPC_NPC_PEER_A_NAME[$DIR]:-}"
  PAD="${SMARTNPC_NPC_PEER_A_DISPLAY[$DIR]:-}"
  PBN="${SMARTNPC_NPC_PEER_B_NAME[$DIR]:-}"
  PBD="${SMARTNPC_NPC_PEER_B_DISPLAY[$DIR]:-}"
  TARGET="$REPO_ROOT/hermes/profiles/$DIR"
  mkdir -p "$TARGET/skills"

  # Copy skills tree (mirror _master exactly — excludes SOUL.md which never
  # lives in _master). We wipe the target first so stale skills removed from
  # _master don't linger. Using cp -r (works in Git Bash, WSL, and Linux;
  # rsync may be unavailable on minimal Windows bash installs).
  rm -rf "$TARGET/skills"
  cp -r "$MASTER/skills" "$TARGET/skills"

  # Seed .env from master ONLY when the NPC has none yet. Each NPC owns
  # its own Langfuse keys (one project per character), so re-rendering must
  # NOT overwrite an existing per-NPC .env. Edit hermes/profiles/<npc>/.env
  # directly to change a NPC's keys; _master/.env stays as a placeholder
  # template for newly-cloned profiles.
  if [[ -f "$MASTER/.env" && ! -f "$TARGET/.env" ]]; then
    cp "$MASTER/.env" "$TARGET/.env"
    echo "seeded: $DIR/.env from _master (placeholder values — fill in real keys)"
  fi

  # Copy scalar templates. Do NOT touch SOUL.md.
  cp "$MASTER/config-overlay.yaml" "$TARGET/config-overlay.yaml"
  cp "$MASTER/cron-recipes.md" "$TARGET/cron-recipes.md"
  cp "$MASTER/critical-policy.md" "$TARGET/critical-policy.md"

  # Gather every rendered file for this NPC. Using \( ... \) so -o binds
  # correctly; -print terminates so xargs sees a single list.
  mapfile -t FILES < <(find "$TARGET/skills" "$TARGET/config-overlay.yaml" "$TARGET/cron-recipes.md" "$TARGET/critical-policy.md" \
    -type f \( -name '*.md' -o -name '*.yaml' \) -print)

  # Use | as sed delimiter (paths and values can contain /).
  for f in "${FILES[@]}"; do
    sed -i \
      -e "s|{{NPC_NAME}}|$NAME|g" \
      -e "s|{{NPC_DISPLAY}}|$DISP|g" \
      -e "s|{{NPC_DIR}}|$DIR|g" \
      -e "s|{{NPC_PORT}}|$PORT|g" \
      -e "s|{{PEER_A_NAME}}|$PAN|g" \
      -e "s|{{PEER_A_DISPLAY}}|$PAD|g" \
      -e "s|{{PEER_B_NAME}}|$PBN|g" \
      -e "s|{{PEER_B_DISPLAY}}|$PBD|g" \
      "$f"
  done

  echo "rendered: $DIR ($NAME / $DISP, port $PORT, peers $PAN + $PBN)"
done

{
  cat <<'EOF'
# hermes/runtime-config.yaml
#
# Generated by scripts/render_profiles.sh from hermes/npcs.yaml.
# Multi-profile fan-out config consumed by smartnpc-mcp --hermes-config.
#
# gateway_url uses ${SMARTNPC_HERMES_GATEWAY_HOST}; smartnpc-mcp expands it
# at startup, falling back to $WSL_IP and then 127.0.0.1.

profiles:
EOF

  idx=0
  total=${#SMARTNPC_NPCS[@]}
  for DIR in "${SMARTNPC_NPCS[@]}"; do
    NAME="${SMARTNPC_NPC_GAME_NAME[$DIR]}"
    PORT="${SMARTNPC_NPC_GATEWAY_PORT[$DIR]}"
    cat <<EOF
  - name: $DIR
    npc_filter: $NAME
    gateway_url: http://\${SMARTNPC_HERMES_GATEWAY_HOST}:$PORT
    conversation: $DIR
    model: hermes-agent
    api_key_env: SMARTNPC_HERMES_KEY
EOF
    idx=$((idx + 1))
    if [ "$idx" -lt "$total" ]; then
      echo
    fi
  done
} > "$RUNTIME_CONFIG"
echo "rendered: hermes/runtime-config.yaml from hermes/npcs.yaml"

# ── Generate mod-side NPC enable list ───────────────────────────────────
# The C# mod reads this JSON to know which NPCs to manage.
# Format: { "GameName": true|false } for ALL NPCs (enabled + disabled).
# This is the single bridge between npcs.yaml and the mod layer.
MOD_NPC_JSON="$REPO_ROOT/smapi-mod/assets/agent_npcs.json"
{
  echo "{"
  total_all=${#SMARTNPC_ALL_NPCS[@]}
  idx=0
  for DIR in "${SMARTNPC_ALL_NPCS[@]}"; do
    NAME="${SMARTNPC_NPC_GAME_NAME[$DIR]}"
    ENABLED="${SMARTNPC_NPC_ENABLED[$DIR]:-true}"
    if [ $((idx + 1)) -lt "$total_all" ]; then
      echo "  \"$NAME\": $ENABLED,"
    else
      echo "  \"$NAME\": $ENABLED"
    fi
    idx=$((idx + 1))
  done
  echo "}"
} > "$MOD_NPC_JSON"
echo "rendered: smapi-mod/assets/agent_npcs.json ($total_all NPCs: ${#SMARTNPC_NPCS[@]} enabled, $((total_all - ${#SMARTNPC_NPCS[@]})) disabled)"

echo ""
echo "done. Sanity check: 'git diff hermes/profiles/ hermes/runtime-config.yaml' should be empty."
